name: .NET CI

on:

# Trigger the workflow on push or pull request events to the main and develop branches
  push:
    branches:
       - main
       - feature/**


  pull_request:
    branches: 
       - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore src/Playground/Playground.csproj

      - name: Build
        run: dotnet build src/Playground/Playground.csproj --no-restore --configuration Release

      - name: Run tests
        run: dotnet test src/Playground.Tests/Playground.Tests.csproj --no-build --verbosity normal

      - name: Pipeline confirmation
        run: echo "Pipeline working."